INSERT INTO "common"("type","value","text","description","sequence",is_deleted,create_by,create_on) VALUES ('Statement','WC','FIFA World Cup',NULL,1,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "common"("type","value","text","description","sequence",is_deleted,create_by,create_on) VALUES ('Statement','EU','UEFA Euro',NULL,2,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "common"("type","value","text","description","sequence",is_deleted,create_by,create_on) VALUES ('Statement','C1','UEFA Champions League',NULL,3,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "common"("type","value","text","description","sequence",is_deleted,create_by,create_on) VALUES ('Statement','C2','UEFA Europa League',NULL,4,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "common"("type","value","text","description","sequence",is_deleted,create_by,create_on) VALUES ('Statement','BPL','Barclays Primier League',NULL,5,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "common"("type","value","text","description","sequence",is_deleted,create_by,create_on) VALUES ('Statement','Bund','Bundesliga',NULL,6,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "common"("type","value","text","description","sequence",is_deleted,create_by,create_on) VALUES ('Statement','Liga','La Liga',NULL,7,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "common"("type","value","text","description","sequence",is_deleted,create_by,create_on) VALUES ('Statement','SerA','Serie A',NULL,8,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "common"("type","value","text","description","sequence",is_deleted,create_by,create_on) VALUES ('Statement','Lig1','Ligue 1',NULL,9,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "common"("type","value","text","description","sequence",is_deleted,create_by,create_on) VALUES ('Guess','THT','Thắng Hòa Thua',NULL,1,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "common"("type","value","text","description","sequence",is_deleted,create_by,create_on) VALUES ('Guess','TS','Tỷ số',NULL,2,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "common"("type","value","text","description","sequence",is_deleted,create_by,create_on) VALUES ('Guess','TX','Tài xỉu',NULL,3,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "common"("type","value","text","description","sequence",is_deleted,create_by,create_on) VALUES ('Guess','DVD','Đội vô địch',NULL,4,FALSE,1,CURRENT_TIMESTAMP);

INSERT INTO "statement"("name","from_date","to_date","history","parent_id",is_deleted,create_by,create_on) VALUES ('World Cup 2018','06/14/2018 22:00','07/15/2018 22:00',NULL,NULL,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "statement"("name","from_date","to_date","history","parent_id",is_deleted,create_by,create_on) VALUES ('Group A',NULL,NULL,NULL,'1',TRUE,1,CURRENT_TIMESTAMP);
INSERT INTO "statement"("name","from_date","to_date","history","parent_id",is_deleted,create_by,create_on) VALUES ('Group B',NULL,NULL,NULL,'1',TRUE,1,CURRENT_TIMESTAMP);
INSERT INTO "statement"("name","from_date","to_date","history","parent_id",is_deleted,create_by,create_on) VALUES ('Group C',NULL,NULL,NULL,'1',TRUE,1,CURRENT_TIMESTAMP);
INSERT INTO "statement"("name","from_date","to_date","history","parent_id",is_deleted,create_by,create_on) VALUES ('Group D',NULL,NULL,NULL,'1',TRUE,1,CURRENT_TIMESTAMP);
INSERT INTO "statement"("name","from_date","to_date","history","parent_id",is_deleted,create_by,create_on) VALUES ('Group E',NULL,NULL,NULL,'1',TRUE,1,CURRENT_TIMESTAMP);
INSERT INTO "statement"("name","from_date","to_date","history","parent_id",is_deleted,create_by,create_on) VALUES ('Group F',NULL,NULL,NULL,'1',TRUE,1,CURRENT_TIMESTAMP);
INSERT INTO "statement"("name","from_date","to_date","history","parent_id",is_deleted,create_by,create_on) VALUES ('Group G',NULL,NULL,NULL,'1',TRUE,1,CURRENT_TIMESTAMP);
INSERT INTO "statement"("name","from_date","to_date","history","parent_id",is_deleted,create_by,create_on) VALUES ('Group H',NULL,NULL,NULL,'1',TRUE,1,CURRENT_TIMESTAMP);

INSERT INTO "team"("name","country","coach","history","logo",is_deleted,create_by,create_on) VALUES ('Russia','Russia','Stanislav Cherchesov',NULL,'Russia.png',TRUE,1,CURRENT_TIMESTAMP);
INSERT INTO "team"("name","country","coach","history","logo",is_deleted,create_by,create_on) VALUES ('Egypt','Egypt','Héctor Cúper',NULL,'Egypt.png',TRUE,1,CURRENT_TIMESTAMP);
INSERT INTO "team"("name","country","coach","history","logo",is_deleted,create_by,create_on) VALUES ('Uruguay','Uruguay','Óscar Tabárez',NULL,'Uruguay.png',TRUE,1,CURRENT_TIMESTAMP);
INSERT INTO "team"("name","country","coach","history","logo",is_deleted,create_by,create_on) VALUES ('Saudi Arabia','Saudi Arabia','Juan Antonio Pizzi',NULL,'Saudi_Arabia.png',TRUE,1,CURRENT_TIMESTAMP);

INSERT INTO "team"("name","country","coach","history","logo",is_deleted,create_by,create_on) VALUES ('Iran','Iran','Carlos Queiroz',NULL,'Iran.png',TRUE,1,CURRENT_TIMESTAMP);
INSERT INTO "team"("name","country","coach","history","logo",is_deleted,create_by,create_on) VALUES ('Morocco','Morocco','Hervé Renard',NULL,'Morocco.png',TRUE,1,CURRENT_TIMESTAMP);
INSERT INTO "team"("name","country","coach","history","logo",is_deleted,create_by,create_on) VALUES ('Portugal','Portugal','Fernando Santos',NULL,'Portugal.png',TRUE,1,CURRENT_TIMESTAMP);
INSERT INTO "team"("name","country","coach","history","logo",is_deleted,create_by,create_on) VALUES ('Spain','Spain','Julen Lopetegui',NULL,'Spain.png',TRUE,1,CURRENT_TIMESTAMP);

INSERT INTO "team"("name","country","coach","history","logo",is_deleted,create_by,create_on) VALUES ('France','France','Didier Deschamps',NULL,'France.png',TRUE,1,CURRENT_TIMESTAMP);
INSERT INTO "team"("name","country","coach","history","logo",is_deleted,create_by,create_on) VALUES ('Peru','Peru','Ricardo Gareca',NULL,'Peru.png',TRUE,1,CURRENT_TIMESTAMP);
INSERT INTO "team"("name","country","coach","history","logo",is_deleted,create_by,create_on) VALUES ('Denmark','Denmark','Åge Hareide',NULL,'Denmark.png',TRUE,1,CURRENT_TIMESTAMP);
INSERT INTO "team"("name","country","coach","history","logo",is_deleted,create_by,create_on) VALUES ('Australia','Australia','Bert van Marwijk',NULL,'Australia.png',TRUE,1,CURRENT_TIMESTAMP);

INSERT INTO "team"("name","country","coach","history","logo",is_deleted,create_by,create_on) VALUES ('Croatia','Croatia','Zlatko Dalić',NULL,'Croatia.png',TRUE,1,CURRENT_TIMESTAMP);
INSERT INTO "team"("name","country","coach","history","logo",is_deleted,create_by,create_on) VALUES ('Iceland','Iceland','Heimir Hallgrímsson',NULL,'Iceland.png',TRUE,1,CURRENT_TIMESTAMP);
INSERT INTO "team"("name","country","coach","history","logo",is_deleted,create_by,create_on) VALUES ('Nigeria','Nigeria','Gernot Rohr',NULL,'Nigeria.png',TRUE,1,CURRENT_TIMESTAMP);
INSERT INTO "team"("name","country","coach","history","logo",is_deleted,create_by,create_on) VALUES ('Argentina','Argentina','Jorge Sampaoli',NULL,'Argentina.png',TRUE,1,CURRENT_TIMESTAMP);

INSERT INTO "team"("name","country","coach","history","logo",is_deleted,create_by,create_on) VALUES ('Brazil','Brazil','Tite',NULL,'Brazil.png',TRUE,1,CURRENT_TIMESTAMP);
INSERT INTO "team"("name","country","coach","history","logo",is_deleted,create_by,create_on) VALUES ('Serbia','Serbia','Mladen Krstajić',NULL,'Serbia.png',TRUE,1,CURRENT_TIMESTAMP);
INSERT INTO "team"("name","country","coach","history","logo",is_deleted,create_by,create_on) VALUES ('Switzerland','Switzerland','Vladimir Petković',NULL,'Switzerland.png',TRUE,1,CURRENT_TIMESTAMP);
INSERT INTO "team"("name","country","coach","history","logo",is_deleted,create_by,create_on) VALUES ('Costa Rica','Costa Rica','Óscar Ramírez',NULL,'Costa_Rica.png',TRUE,1,CURRENT_TIMESTAMP);

INSERT INTO "team"("name","country","coach","history","logo",is_deleted,create_by,create_on) VALUES ('Germany','Germany','Joachim Löw',NULL,'Germany.png',TRUE,1,CURRENT_TIMESTAMP);
INSERT INTO "team"("name","country","coach","history","logo",is_deleted,create_by,create_on) VALUES ('Mexico','Mexico','Juan Carlos Osorio',NULL,'Mexico.png',TRUE,1,CURRENT_TIMESTAMP);
INSERT INTO "team"("name","country","coach","history","logo",is_deleted,create_by,create_on) VALUES ('Sweden','Sweden','Janne Andersson',NULL,'Sweden.png',TRUE,1,CURRENT_TIMESTAMP);
INSERT INTO "team"("name","country","coach","history","logo",is_deleted,create_by,create_on) VALUES ('South Korea','South Korea','Shin Tae-yong',NULL,'South_Korea.png',TRUE,1,CURRENT_TIMESTAMP);

INSERT INTO "team"("name","country","coach","history","logo",is_deleted,create_by,create_on) VALUES ('Belgium','Belgium','Roberto Martínez',NULL,'Belgium.png',TRUE,1,CURRENT_TIMESTAMP);
INSERT INTO "team"("name","country","coach","history","logo",is_deleted,create_by,create_on) VALUES ('England','England','Gareth Southgate',NULL,'England.png',TRUE,1,CURRENT_TIMESTAMP);
INSERT INTO "team"("name","country","coach","history","logo",is_deleted,create_by,create_on) VALUES ('Tunisia','Tunisia','Nabil Maâloul',NULL,'Tunisia.png',TRUE,1,CURRENT_TIMESTAMP);
INSERT INTO "team"("name","country","coach","history","logo",is_deleted,create_by,create_on) VALUES ('Panama','Panama','Hernán Darío Gómez',NULL,'Panama.png',TRUE,1,CURRENT_TIMESTAMP);

INSERT INTO "team"("name","country","coach","history","logo",is_deleted,create_by,create_on) VALUES ('Poland','Poland','Adam Nawałka',NULL,'Poland.png',TRUE,1,CURRENT_TIMESTAMP);
INSERT INTO "team"("name","country","coach","history","logo",is_deleted,create_by,create_on) VALUES ('Senegal','Senegal','Aliou Cissé',NULL,'Senegal.png',TRUE,1,CURRENT_TIMESTAMP);
INSERT INTO "team"("name","country","coach","history","logo",is_deleted,create_by,create_on) VALUES ('Japan','Japan','Akira Nishino',NULL,'Japan.png',TRUE,1,CURRENT_TIMESTAMP);
INSERT INTO "team"("name","country","coach","history","logo",is_deleted,create_by,create_on) VALUES ('Colombia','Colombia','José Pékerman',NULL,'Colombia.png',TRUE,1,CURRENT_TIMESTAMP);

INSERT INTO "team"("name","country","coach","history","logo",is_deleted,create_by,create_on) VALUES ('TBD',NULL,'TBD',NULL,'TBD.png',TRUE,1,CURRENT_TIMESTAMP);

INSERT INTO "join"("team_id","statement_id",is_deleted,create_by,create_on) VALUES (1,2,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "join"("team_id","statement_id",is_deleted,create_by,create_on) VALUES (2,2,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "join"("team_id","statement_id",is_deleted,create_by,create_on) VALUES (3,2,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "join"("team_id","statement_id",is_deleted,create_by,create_on) VALUES (4,2,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "join"("team_id","statement_id",is_deleted,create_by,create_on) VALUES (5,3,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "join"("team_id","statement_id",is_deleted,create_by,create_on) VALUES (6,3,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "join"("team_id","statement_id",is_deleted,create_by,create_on) VALUES (7,3,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "join"("team_id","statement_id",is_deleted,create_by,create_on) VALUES (8,3,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "join"("team_id","statement_id",is_deleted,create_by,create_on) VALUES (9,4,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "join"("team_id","statement_id",is_deleted,create_by,create_on) VALUES (10,4,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "join"("team_id","statement_id",is_deleted,create_by,create_on) VALUES (11,4,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "join"("team_id","statement_id",is_deleted,create_by,create_on) VALUES (12,4,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "join"("team_id","statement_id",is_deleted,create_by,create_on) VALUES (13,5,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "join"("team_id","statement_id",is_deleted,create_by,create_on) VALUES (14,5,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "join"("team_id","statement_id",is_deleted,create_by,create_on) VALUES (15,5,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "join"("team_id","statement_id",is_deleted,create_by,create_on) VALUES (16,5,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "join"("team_id","statement_id",is_deleted,create_by,create_on) VALUES (17,6,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "join"("team_id","statement_id",is_deleted,create_by,create_on) VALUES (18,6,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "join"("team_id","statement_id",is_deleted,create_by,create_on) VALUES (19,6,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "join"("team_id","statement_id",is_deleted,create_by,create_on) VALUES (20,6,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "join"("team_id","statement_id",is_deleted,create_by,create_on) VALUES (21,7,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "join"("team_id","statement_id",is_deleted,create_by,create_on) VALUES (22,7,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "join"("team_id","statement_id",is_deleted,create_by,create_on) VALUES (23,7,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "join"("team_id","statement_id",is_deleted,create_by,create_on) VALUES (24,7,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "join"("team_id","statement_id",is_deleted,create_by,create_on) VALUES (25,8,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "join"("team_id","statement_id",is_deleted,create_by,create_on) VALUES (26,8,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "join"("team_id","statement_id",is_deleted,create_by,create_on) VALUES (27,8,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "join"("team_id","statement_id",is_deleted,create_by,create_on) VALUES (28,8,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "join"("team_id","statement_id",is_deleted,create_by,create_on) VALUES (29,9,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "join"("team_id","statement_id",is_deleted,create_by,create_on) VALUES (30,9,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "join"("team_id","statement_id",is_deleted,create_by,create_on) VALUES (31,9,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "join"("team_id","statement_id",is_deleted,create_by,create_on) VALUES (32,9,FALSE,1,CURRENT_TIMESTAMP);


INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('6/14/2018  10:00:00 PM',1,4,NULL,NULL,NULL,NULL,TRUE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('6/15/2018  7:00:00 PM',2,3,NULL,NULL,NULL,NULL,TRUE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('6/20/2018  1:00:00 AM',1,2,NULL,NULL,NULL,NULL,TRUE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('6/20/2018  10:00:00 PM',3,4,NULL,NULL,NULL,NULL,TRUE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('6/25/2018  9:00:00 PM',3,1,NULL,NULL,NULL,NULL,TRUE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('6/25/2018  9:00:00 PM',4,2,NULL,NULL,NULL,NULL,TRUE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('6/15/2018  10:00:00 PM',6,5,NULL,NULL,NULL,NULL,TRUE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('6/16/2018  1:00:00 AM',7,8,NULL,NULL,NULL,NULL,TRUE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('6/20/2018  7:00:00 PM',7,6,NULL,NULL,NULL,NULL,TRUE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('6/21/2018  1:00:00 AM',5,8,NULL,NULL,NULL,NULL,TRUE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('6/26/2018  1:00:00 AM',8,6,NULL,NULL,NULL,NULL,TRUE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('6/27/2018  1:00:00 AM',5,7,NULL,NULL,NULL,NULL,TRUE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('6/16/2018  5:00:00 PM',9,12,NULL,NULL,NULL,NULL,TRUE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('6/16/2018  11:00:00 PM',10,11,NULL,NULL,NULL,NULL,TRUE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('6/21/2018  7:00:00 PM',11,12,NULL,NULL,NULL,NULL,TRUE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('6/21/2018  10:00:00 PM',9,10,NULL,NULL,NULL,NULL,TRUE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('6/26/2018  9:00:00 PM',9,11,NULL,NULL,NULL,NULL,TRUE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('6/27/2018  9:00:00 PM',12,10,NULL,NULL,NULL,NULL,TRUE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('6/16/2018  8:00:00 PM',16,14,NULL,NULL,NULL,NULL,TRUE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('6/17/2018  2:00:00 AM',13,15,NULL,NULL,NULL,NULL,TRUE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('6/22/2018  1:00:00 AM',16,13,NULL,NULL,NULL,NULL,TRUE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('6/22/2018  10:00:00 PM',15,14,NULL,NULL,NULL,NULL,TRUE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('6/27/2018  1:00:00 AM',15,16,NULL,NULL,NULL,NULL,TRUE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('6/27/2018  1:00:00 AM',14,13,NULL,NULL,NULL,NULL,TRUE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('6/17/2018  7:00:00 PM',20,18,NULL,NULL,NULL,NULL,TRUE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('6/18/2018  1:00:00 AM',17,19,NULL,NULL,NULL,NULL,TRUE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('6/22/2018  7:00:00 PM',17,20,NULL,NULL,NULL,NULL,TRUE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('6/23/2018  1:00:00 AM',18,19,NULL,NULL,NULL,NULL,TRUE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('6/28/2018  1:00:00 AM',18,17,NULL,NULL,NULL,NULL,TRUE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('6/28/2018  1:00:00 AM',19,20,NULL,NULL,NULL,NULL,TRUE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('6/17/2018  10:00:00 PM',21,22,NULL,NULL,NULL,NULL,TRUE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('6/18/2018  7:00:00 PM',23,24,NULL,NULL,NULL,NULL,TRUE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('6/23/2018  10:00:00 PM',24,22,NULL,NULL,NULL,NULL,TRUE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('6/24/2018  1:00:00 AM',21,23,NULL,NULL,NULL,NULL,TRUE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('6/27/2018  9:00:00 PM',24,21,NULL,NULL,NULL,NULL,TRUE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('6/27/2018  9:00:00 PM',22,23,NULL,NULL,NULL,NULL,TRUE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('6/18/2018  10:00:00 PM',25,28,NULL,NULL,NULL,NULL,TRUE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('6/19/2018  1:00:00 AM',27,26,NULL,NULL,NULL,NULL,TRUE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('6/23/2018  7:00:00 PM',25,27,NULL,NULL,NULL,NULL,TRUE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('6/24/2018  7:00:00 PM',26,28,NULL,NULL,NULL,NULL,TRUE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('6/29/2018  1:00:00 AM',26,25,NULL,NULL,NULL,NULL,TRUE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('6/29/2018  1:00:00 AM',28,27,NULL,NULL,NULL,NULL,TRUE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('6/19/2018  7:00:00 PM',32,31,NULL,NULL,NULL,NULL,TRUE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('6/19/2018  10:00:00 PM',29,30,NULL,NULL,NULL,NULL,TRUE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('6/24/2018  10:00:00 PM',31,30,NULL,NULL,NULL,NULL,TRUE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('6/25/2018  1:00:00 AM',29,32,NULL,NULL,NULL,NULL,TRUE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('6/28/2018  9:00:00 PM',31,29,NULL,NULL,NULL,NULL,TRUE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('6/28/2018  9:00:00 PM',30,32,NULL,NULL,NULL,NULL,TRUE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('6/30/2018  9:00:00 PM',33,33,NULL,NULL,NULL,NULL,FALSE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('7/1/2018  1:00:00 AM',33,33,NULL,NULL,NULL,NULL,FALSE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('7/1/2018  9:00:00 PM',33,33,NULL,NULL,NULL,NULL,FALSE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('7/2/2018  1:00:00 AM',33,33,NULL,NULL,NULL,NULL,FALSE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('7/2/2018  9:00:00 PM',33,33,NULL,NULL,NULL,NULL,FALSE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('7/3/2018  1:00:00 AM',33,33,NULL,NULL,NULL,NULL,FALSE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('7/3/2018  9:00:00 PM',33,33,NULL,NULL,NULL,NULL,FALSE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('7/4/2018  1:00:00 AM',33,33,NULL,NULL,NULL,NULL,FALSE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('7/6/2018  9:00:00 PM',33,33,NULL,NULL,NULL,NULL,FALSE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('7/7/2018  1:00:00 AM',33,33,NULL,NULL,NULL,NULL,FALSE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('7/7/2018  9:00:00 PM',33,33,NULL,NULL,NULL,NULL,FALSE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('7/8/2018  1:00:00 AM',33,33,NULL,NULL,NULL,NULL,FALSE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('7/11/2018  1:00:00 AM',33,33,NULL,NULL,NULL,NULL,FALSE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('7/12/2018  1:00:00 AM',33,33,NULL,NULL,NULL,NULL,FALSE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('7/14/2018  9:00:00 PM',33,33,NULL,NULL,NULL,NULL,FALSE,FALSE,1,CURRENT_TIMESTAMP);
INSERT INTO "calendar"("competition_date","team1_id","team2_id","stadium","referee","squad1","squad2","is_group_match",is_deleted,create_by,create_on) VALUES ('7/15/2018  10:00:00 PM',33,33,NULL,NULL,NULL,NULL,FALSE,FALSE,1,CURRENT_TIMESTAMP);
